In [2]:
import pandas as pd 
df = pd.read_csv("ElectricCarData_Clean.csv")
print(df)

           Brand                            Model  AccelSec  TopSpeed_KmH  \
0         Tesla     Model 3 Long Range Dual Motor       4.6           233
1    Volkswagen                         ID.3 Pure      10.0           160
2      Polestar                                 2       4.7           210
3           BMW                              iX3        6.8           180
4         Honda                                e        9.5           145
..           ...                              ...       ...           ...
98       Nissan                       Ariya 63kWh       7.5           160
99         Audi     e-tron S Sportback 55 quattro       4.5           210
100      Nissan               Ariya e-4ORCE 63kWh       5.9           200
101      Nissan   Ariya e-4ORCE 87kWh Performance       5.1           200
102       Byton                 M-Byte 95 kWh 2WD       7.5           190

     Range_Km  Efficiency_WhKm FastCharge_KmH RapidCharge PowerTrain  \
0         450              161            940         Yes        AWD
1         270              167            250         Yes        RWD
2         400              181            620         Yes        AWD
3         360              206            560         Yes        RWD
4         170              168            190         Yes        RWD
..        ...              ...            ...         ...        ...
98        330              191            440         Yes        FWD
99        335              258            540         Yes        AWD
100       325              194            440         Yes        AWD
101       375              232            450         Yes        AWD
102       400              238            480         Yes        AWD

       PlugType  BodyStyle Segment  Seats  PriceEuro
0    Type 2 CCS      Sedan       D      5      55480
1    Type 2 CCS  Hatchback       C      5      30000
2    Type 2 CCS   Liftback       D      5      56440
3    Type 2 CCS        SUV       D      5      68040
4    Type 2 CCS  Hatchback       B      4      32997
..          ...        ...     ...    ...        ...
98   Type 2 CCS  Hatchback       C      5      45000
99   Type 2 CCS        SUV       E      5      96050
100  Type 2 CCS  Hatchback       C      5      50000
101  Type 2 CCS  Hatchback       C      5      65000
102  Type 2 CCS        SUV       E      5      62000

[103 rows x 14 columns]

In [3]:
df.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040
4,Honda,e,9.5,145,170,168,190,Yes,RWD,Type 2 CCS,Hatchback,B,4,32997

In [4]:
df.shape

(103, 14)

In [5]:
df.columns

Index(['Brand', 'Model', 'AccelSec', 'TopSpeed_KmH', 'Range_Km',
       'Efficiency_WhKm', 'FastCharge_KmH', 'RapidCharge', 'PowerTrain',
       'PlugType', 'BodyStyle', 'Segment', 'Seats', 'PriceEuro'],
      dtype='str')

In [6]:
df.describe()

,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,Seats,PriceEuro
count,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000
mean,7.396117,179.194175,338.786408,189.165049,4.883495,55811.563107
std,3.017430,43.573030,126.014444,29.566839,0.795834,34134.665280
min,2.100000,123.000000,95.000000,104.000000,2.000000,20129.000000
25%,5.100000,150.000000,250.000000,168.000000,5.000000,34429.500000
50%,7.300000,160.000000,340.000000,180.000000,5.000000,45000.000000
75%,9.000000,200.000000,400.000000,203.000000,5.000000,65000.000000
max,22.400000,410.000000,970.000000,273.000000,7.000000,215000.000000

In [7]:
df.isnull().sum()

Brand              0
Model              0
AccelSec           0
TopSpeed_KmH       0
Range_Km           0
Efficiency_WhKm    0
FastCharge_KmH     0
RapidCharge        0
PowerTrain         0
PlugType           0
BodyStyle          0
Segment            0
Seats              0
PriceEuro          0
dtype: int64

In [8]:
df["Brand"]

0           Tesla
1      Volkswagen
2        Polestar
3             BMW
4           Honda
          ...
98         Nissan
99           Audi
100        Nissan
101        Nissan
102         Byton
Name: Brand, Length: 103, dtype: str

In [9]:
df[df["TopSpeed_KmH"]>160]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040
5,Lucid,Air,2.8,250,610,180,620,Yes,AWD,Type 2 CCS,Sedan,F,5,105000
8,Tesla,Model 3 Standard Range Plus,5.6,225,310,153,650,Yes,RWD,Type 2 CCS,Sedan,D,5,46380
9,Audi,Q4 e-tron,6.3,180,400,193,540,Yes,AWD,Type 2 CCS,SUV,D,5,55000
10,Mercedes,EQC 400 4MATIC,5.1,180,370,216,440,Yes,AWD,Type 2 CCS,SUV,D,5,69484
12,Hyundai,Kona Electric 64 kWh,7.9,167,400,160,380,Yes,FWD,Type 2 CCS,SUV,B,5,40795
13,BMW,i4,4.0,200,450,178,650,Yes,RWD,Type 2 CCS,Sedan,D,5,65000
14,Hyundai,IONIQ Electric,9.7,165,250,153,210,Yes,FWD,Type 2 CCS,Liftback,C,5,34459
16,Porsche,Taycan Turbo S,2.8,260,375,223,780,Yes,AWD,Type 2 CCS,Sedan,F,4,180781
21,Tesla,Model Y Long Range Dual Motor,5.1,217,425,171,930,Yes,AWD,Type 2 CCS,SUV,D,7,58620
23,Audi,e-tron GT,3.5,240,425,197,850,Yes,AWD,Type 2 CCS,Sedan,F,4,125000
24,Tesla,Model 3 Long Range Performance,3.4,261,435,167,910,Yes,AWD,Type 2 CCS,Sedan,D,5,61480
27,Volvo,XC40 P8 AWD Recharge,4.9,180,375,200,470,Yes,AWD,Type 2 CCS,SUV,C,5,60437
30,Audi,e-tron 50 quattro,6.8,190,280,231,450,Yes,AWD,Type 2 CCS,SUV,E,5,67358
31,Kia,e-Niro 64 kWh,7.8,167,370,173,350,Yes,FWD,Type 2 CCS,SUV,C,5,38105
33,Tesla,Cybertruck Tri Motor,3.0,210,750,267,710,Yes,AWD,Type 2 CCS,Pickup,N,6,75000
39,Mercedes,EQA,5.0,200,350,171,440,Yes,AWD,Type 2 CCS,SUV,C,5,45000
40,Tesla,Model S Long Range,3.8,250,515,184,560,Yes,AWD,Type 2,Liftback,F,5,79990
42,Audi,e-tron Sportback 55 quattro,5.7,200,380,228,610,Yes,AWD,Type 2 CCS,SUV,E,5,81639
45,Kia,e-Soul 64 kWh,7.9,167,365,175,340,Yes,FWD,Type 2 CCS,SUV,B,5,36837
47,Porsche,Taycan 4S,4.0,250,365,195,730,Yes,AWD,Type 2 CCS,Sedan,F,4,102945
50,Audi,e-tron 55 quattro,5.7,200,365,237,590,Yes,AWD,Type 2 CCS,SUV,E,5,79445
51,Tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000
54,Tesla,Model X Long Range,4.6,250,450,211,490,Yes,AWD,Type 2,SUV,F,7,85990
59,Tesla,Model S Performance,2.5,261,505,188,550,Yes,AWD,Type 2,Liftback,F,5,96990
61,Tesla,Model Y Long Range Performance,3.7,241,410,177,900,Yes,AWD,Type 2 CCS,SUV,D,7,65620
63,Jaguar,I-Pace,4.8,200,365,232,340,Yes,AWD,Type 2 CCS,SUV,E,5,75351
64,Ford,Mustang Mach-E ER RWD,7.0,180,450,200,430,Yes,RWD,Type 2 CCS,SUV,D,5,54475
65,Porsche,Taycan 4S Plus,4.0,250,425,197,890,Yes,AWD,Type 2 CCS,Sedan,F,4,109302
67,Tesla,Cybertruck Dual Motor,5.0,190,460,261,710,Yes,AWD,Type 2 CCS,Pickup,N,6,55000
69,Ford,Mustang Mach-E ER AWD,6.0,180,430,209,410,Yes,AWD,Type 2 CCS,SUV,D,5,62900
72,Porsche,Taycan Cross Turismo,3.5,250,385,217,770,Yes,AWD,Type 2 CCS,Station,F,4,150000
73,Byton,M-Byte 95 kWh 4WD,5.5,190,390,244,460,Yes,AWD,Type 2 CCS,SUV,E,5,64000
76,Audi,Q4 Sportback e-tron,6.3,180,410,188,550,Yes,AWD,Type 2 CCS,SUV,D,5,57500
78,Ford,Mustang Mach-E SR AWD,6.0,180,340,206,360,Yes,AWD,Type 2 CCS,SUV,D,5,54000
79,Porsche,Taycan Turbo,3.2,260,390,215,810,Yes,AWD,Type 2 CCS,Sedan,F,4,148301
81,Tesla,Model X Performance,2.8,250,440,216,480,Yes,AWD,Type 2,SUV,F,7,102990
83,Ford,Mustang Mach-E SR RWD,6.6,180,360,194,380,Yes,RWD,Type 2 CCS,SUV,D,5,46900
86,Tesla,Cybertruck Single Motor,7.0,180,390,256,740,Yes,RWD,Type 2 CCS,Pickup,N,6,45000
87,Audi,e-tron Sportback 50 quattro,6.8,190,295,219,470,Yes,AWD,Type 2 CCS,SUV,E,5,69551
88,Skoda,Enyaq iV vRS,6.2,180,400,193,540,Yes,AWD,Type 2 CCS,SUV,C,5,47500
90,Audi,e-tron S 55 quattro,4.5,210,320,270,510,Yes,AWD,Type 2 CCS,SUV,E,5,93800
92,Kia,e-Soul 64 kWh,7.9,167,365,175,320,Yes,FWD,Type 2 CCS,SUV,B,5,36837
93,Nissan,Ariya e-4ORCE 87kWh,5.7,200,420,207,500,Yes,AWD,Type 2 CCS,Hatchback,C,5,57500
97,Byton,M-Byte 72 kWh 2WD,7.5,190,325,222,420,Yes,RWD,Type 2 CCS,SUV,E,5,53500
99,Audi,e-tron S Sportback 55 quattro,4.5,210,335,258,540,Yes,AWD,Type 2 CCS,SUV,E,5,96050
100,Nissan,Ariya e-4ORCE 63kWh,5.9,200,325,194,440,Yes,AWD,Type 2 CCS,Hatchback,C,5,50000
101,Nissan,Ariya e-4ORCE 87kWh Performance,5.1,200,375,232,450,Yes,AWD,Type 2 CCS,Hatchback,C,5,65000
102,Byton,M-Byte 95 kWh 2WD,7.5,190,400,238,480,Yes,AWD,Type 2 CCS,SUV,E,5,62000

In [10]:
df[df["TopSpeed_KmH"]>400]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
51,Tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000

In [11]:
df[df["Range_Km"]>800]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
51,Tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000

In [12]:
df[df["Range_Km"]>500]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
5,Lucid,Air,2.8,250,610,180,620,Yes,AWD,Type 2 CCS,Sedan,F,5,105000
33,Tesla,Cybertruck Tri Motor,3.0,210,750,267,710,Yes,AWD,Type 2 CCS,Pickup,N,6,75000
40,Tesla,Model S Long Range,3.8,250,515,184,560,Yes,AWD,Type 2,Liftback,F,5,79990
48,Lightyear,One,10.0,150,575,104,540,Yes,AWD,Type 2 CCS,Liftback,F,5,149000
51,Tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000
59,Tesla,Model S Performance,2.5,261,505,188,550,Yes,AWD,Type 2,Liftback,F,5,96990

In [13]:
df.sort_values("Range_Km")

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
91,Smart,EQ fortwo cabrio,11.9,130,95,176,-,No,RWD,Type 2,Cabrio,A,2,24565
77,Smart,EQ forfour,12.7,130,95,176,-,No,RWD,Type 2,Hatchback,A,4,22030
82,Smart,EQ fortwo coupe,11.6,130,100,167,-,No,RWD,Type 2,Hatchback,A,2,21387
57,Renault,Twingo ZE,12.6,135,130,164,-,No,RWD,Type 2,Hatchback,A,4,24790
68,Renault,Kangoo Maxi ZE 33,22.4,130,160,194,-,No,FWD,Type 2,SPV,N,5,38000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,Tesla,Model S Long Range,3.8,250,515,184,560,Yes,AWD,Type 2,Liftback,F,5,79990
48,Lightyear,One,10.0,150,575,104,540,Yes,AWD,Type 2 CCS,Liftback,F,5,149000
5,Lucid,Air,2.8,250,610,180,620,Yes,AWD,Type 2 CCS,Sedan,F,5,105000
33,Tesla,Cybertruck Tri Motor,3.0,210,750,267,710,Yes,AWD,Type 2 CCS,Pickup,N,6,75000
51,Tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000

In [14]:
df.groupby("Range_Km").mean(numeric_only=True)

           AccelSec  TopSpeed_KmH  Efficiency_WhKm     Seats      PriceEuro
Range_Km
95        12.300000    130.000000       176.000000  3.000000   23297.500000
100       11.600000    130.000000       167.000000  2.000000   21387.000000
130       12.600000    135.000000       164.000000  4.000000   24790.000000
160       22.400000    130.000000       194.000000  5.000000   38000.000000
170        8.900000    145.000000       168.000000  4.000000   34459.000000
180        9.000000    150.000000       178.000000  5.000000   32646.000000
185        7.300000    150.000000       156.000000  4.000000   31681.000000
190       11.800000    136.500000       184.000000  6.000000   32573.000000
195       12.166667    130.000000       166.000000  4.000000   22028.000000
220        8.050000    142.000000       178.500000  5.000000   29617.000000
225        9.000000    140.000000       156.000000  5.000000   25500.000000
230        8.400000    158.500000       167.500000  4.500000   37329.500000
235        8.550000    152.500000       164.000000  4.500000   36208.500000
250        9.100000    152.500000       171.500000  4.666667   36507.000000
255        9.933333    146.666667       163.666667  5.000000   32735.000000
270        8.750000    160.000000       180.000000  5.000000   40000.000000
275        8.100000    150.000000       164.000000  5.000000   29414.000000
280        6.800000    190.000000       231.000000  5.000000   67358.000000
290       10.000000    160.000000       179.000000  5.000000   35000.000000
295        6.800000    190.000000       219.000000  5.000000   69551.000000
310        7.550000    182.500000       160.500000  5.000000   39756.500000
315       11.400000    135.000000       165.000000  5.000000   31184.000000
320        6.750000    185.000000       225.500000  5.000000   65650.000000
325        6.900000    182.333333       196.000000  5.000000   46912.333333
330        8.750000    150.000000       232.000000  6.000000   57815.500000
335        6.933333    170.000000       206.333333  5.000000   58004.333333
340        6.866667    166.666667       182.666667  5.000000   42854.000000
350        7.000000    180.000000       168.500000  5.000000   39000.000000
360        6.700000    180.000000       200.000000  5.000000   57470.000000
365        6.060000    196.800000       202.800000  4.800000   66283.000000
370        6.450000    173.500000       194.500000  5.000000   53794.500000
375        4.266667    213.333333       218.333333  4.666667  102072.666667
380        5.700000    200.000000       228.000000  5.000000   81639.000000
385        3.500000    250.000000       217.000000  4.000000  150000.000000
390        5.233333    210.000000       238.333333  5.000000   85767.000000
400        6.600000    181.166667       193.000000  5.000000   51122.500000
410        5.000000    210.500000       182.500000  6.000000   61560.000000
420        7.333333    173.333333       191.000000  5.000000   47500.000000
425        4.775000    216.750000       186.500000  4.750000   84480.500000
430        6.000000    180.000000       209.000000  5.000000   62900.000000
435        3.400000    261.000000       167.000000  5.000000   61480.000000
440        6.100000    190.000000       196.333333  5.333333   64642.000000
450        5.050000    215.750000       187.500000  5.500000   65236.250000
460        5.000000    190.000000       261.000000  6.000000   55000.000000
505        2.500000    261.000000       188.000000  5.000000   96990.000000
515        3.800000    250.000000       184.000000  5.000000   79990.000000
575       10.000000    150.000000       104.000000  5.000000  149000.000000
610        2.800000    250.000000       180.000000  5.000000  105000.000000
750        3.000000    210.000000       267.000000  6.000000   75000.000000
970        2.100000    410.000000       206.000000  4.000000  215000.000000

In [15]:
import numpy as np
df.loc[0,"Age"] = np.nan

In [16]:
df.isnull().sum()

Brand                0
Model                0
AccelSec             0
TopSpeed_KmH         0
Range_Km             0
Efficiency_WhKm      0
FastCharge_KmH       0
RapidCharge          0
PowerTrain           0
PlugType             0
BodyStyle            0
Segment              0
Seats                0
PriceEuro            0
Age                103
dtype: int64

In [18]:
df.loc[1,"Age"] = 22

In [20]:
df["Age"].fillna(df["Age"].mean(),inplace = True)

C:\Users\adity\AppData\Local\Temp\ipykernel_1276\1588258379.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Age"].mean(),inplace = True)

0      22.0
1      22.0
2      22.0
3      22.0
4      22.0
       ...
98     22.0
99     22.0
100    22.0
101    22.0
102    22.0
Name: Age, Length: 103, dtype: float64

In [21]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
98     False
99     False
100    False
101    False
102    False
Length: 103, dtype: bool

In [22]:
df.sort_values("Age")

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro,Age
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000,22.0
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480,NaN
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440,NaN
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040,NaN
4,Honda,e,9.5,145,170,168,190,Yes,RWD,Type 2 CCS,Hatchback,B,4,32997,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,Nissan,Ariya 63kWh,7.5,160,330,191,440,Yes,FWD,Type 2 CCS,Hatchback,C,5,45000,NaN
99,Audi,e-tron S Sportback 55 quattro,4.5,210,335,258,540,Yes,AWD,Type 2 CCS,SUV,E,5,96050,NaN
100,Nissan,Ariya e-4ORCE 63kWh,5.9,200,325,194,440,Yes,AWD,Type 2 CCS,Hatchback,C,5,50000,NaN
101,Nissan,Ariya e-4ORCE 87kWh Performance,5.1,200,375,232,450,Yes,AWD,Type 2 CCS,Hatchback,C,5,65000,NaN
102,Byton,M-Byte 95 kWh 2WD,7.5,190,400,238,480,Yes,AWD,Type 2 CCS,SUV,E,5,62000,NaN

In [23]:
df.loc[2,"Age"] = 24

In [24]:
df.loc[7,"Age"] = 12

In [25]:
df.loc[9,"Age"] = 78

In [26]:
df.sort_values("Age")

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro,Age
7,Peugeot,e-208,8.1,150,275,164,420,Yes,FWD,Type 2 CCS,Hatchback,B,5,29682,12.0
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000,22.0
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440,24.0
9,Audi,Q4 e-tron,6.3,180,400,193,540,Yes,AWD,Type 2 CCS,SUV,D,5,55000,78.0
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,Nissan,Ariya 63kWh,7.5,160,330,191,440,Yes,FWD,Type 2 CCS,Hatchback,C,5,45000,NaN
99,Audi,e-tron S Sportback 55 quattro,4.5,210,335,258,540,Yes,AWD,Type 2 CCS,SUV,E,5,96050,NaN
100,Nissan,Ariya e-4ORCE 63kWh,5.9,200,325,194,440,Yes,AWD,Type 2 CCS,Hatchback,C,5,50000,NaN
101,Nissan,Ariya e-4ORCE 87kWh Performance,5.1,200,375,232,450,Yes,AWD,Type 2 CCS,Hatchback,C,5,65000,NaN
102,Byton,M-Byte 95 kWh 2WD,7.5,190,400,238,480,Yes,AWD,Type 2 CCS,SUV,E,5,62000,NaN

In [27]:
df.sort_index()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro,Age
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480,NaN
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000,22.0
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440,24.0
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040,NaN
4,Honda,e,9.5,145,170,168,190,Yes,RWD,Type 2 CCS,Hatchback,B,4,32997,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,Nissan,Ariya 63kWh,7.5,160,330,191,440,Yes,FWD,Type 2 CCS,Hatchback,C,5,45000,NaN
99,Audi,e-tron S Sportback 55 quattro,4.5,210,335,258,540,Yes,AWD,Type 2 CCS,SUV,E,5,96050,NaN
100,Nissan,Ariya e-4ORCE 63kWh,5.9,200,325,194,440,Yes,AWD,Type 2 CCS,Hatchback,C,5,50000,NaN
101,Nissan,Ariya e-4ORCE 87kWh Performance,5.1,200,375,232,450,Yes,AWD,Type 2 CCS,Hatchback,C,5,65000,NaN
102,Byton,M-Byte 95 kWh 2WD,7.5,190,400,238,480,Yes,AWD,Type 2 CCS,SUV,E,5,62000,NaN

In [28]:
df[df["Age"]>20]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro,Age
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000,22.0
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440,24.0
9,Audi,Q4 e-tron,6.3,180,400,193,540,Yes,AWD,Type 2 CCS,SUV,D,5,55000,78.0

In [29]:
df[df["Age"]>60 & (df["Age"]<80)]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro,Age
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000,22.0
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440,24.0
7,Peugeot,e-208,8.1,150,275,164,420,Yes,FWD,Type 2 CCS,Hatchback,B,5,29682,12.0
9,Audi,Q4 e-tron,6.3,180,400,193,540,Yes,AWD,Type 2 CCS,SUV,D,5,55000,78.0

In [30]:
df[df["Age"]>30 | (df["Age"]<40)]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro,Age
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000,22.0
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440,24.0
7,Peugeot,e-208,8.1,150,275,164,420,Yes,FWD,Type 2 CCS,Hatchback,B,5,29682,12.0
9,Audi,Q4 e-tron,6.3,180,400,193,540,Yes,AWD,Type 2 CCS,SUV,D,5,55000,78.0

In [31]:
df.head(50)

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro,Age
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480,NaN
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000,22.0
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440,24.0
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040,NaN
4,Honda,e,9.5,145,170,168,190,Yes,RWD,Type 2 CCS,Hatchback,B,4,32997,NaN
5,Lucid,Air,2.8,250,610,180,620,Yes,AWD,Type 2 CCS,Sedan,F,5,105000,NaN
6,Volkswagen,e-Golf,9.6,150,190,168,220,Yes,FWD,Type 2 CCS,Hatchback,C,5,31900,NaN
7,Peugeot,e-208,8.1,150,275,164,420,Yes,FWD,Type 2 CCS,Hatchback,B,5,29682,12.0
8,Tesla,Model 3 Standard Range Plus,5.6,225,310,153,650,Yes,RWD,Type 2 CCS,Sedan,D,5,46380,NaN
9,Audi,Q4 e-tron,6.3,180,400,193,540,Yes,AWD,Type 2 CCS,SUV,D,5,55000,78.0
10,Mercedes,EQC 400 4MATIC,5.1,180,370,216,440,Yes,AWD,Type 2 CCS,SUV,D,5,69484,NaN
11,Nissan,Leaf,7.9,144,220,164,230,Yes,FWD,Type 2 CHAdeMO,Hatchback,C,5,29234,NaN
12,Hyundai,Kona Electric 64 kWh,7.9,167,400,160,380,Yes,FWD,Type 2 CCS,SUV,B,5,40795,NaN
13,BMW,i4,4.0,200,450,178,650,Yes,RWD,Type 2 CCS,Sedan,D,5,65000,NaN
14,Hyundai,IONIQ Electric,9.7,165,250,153,210,Yes,FWD,Type 2 CCS,Liftback,C,5,34459,NaN
15,Volkswagen,ID.3 Pro S,7.9,160,440,175,590,Yes,RWD,Type 2 CCS,Hatchback,C,4,40936,NaN
16,Porsche,Taycan Turbo S,2.8,260,375,223,780,Yes,AWD,Type 2 CCS,Sedan,F,4,180781,NaN
17,Volkswagen,e-Up!,11.9,130,195,166,170,Yes,FWD,Type 2 CCS,Hatchback,A,4,21421,NaN
18,MG,ZS EV,8.2,140,220,193,260,Yes,FWD,Type 2 CCS,SUV,B,5,30000,NaN
19,Mini,Cooper SE,7.3,150,185,156,260,Yes,FWD,Type 2 CCS,Hatchback,B,4,31681,NaN
20,Opel,Corsa-e,8.1,150,275,164,420,Yes,FWD,Type 2 CCS,Hatchback,B,5,29146,NaN
21,Tesla,Model Y Long Range Dual Motor,5.1,217,425,171,930,Yes,AWD,Type 2 CCS,SUV,D,7,58620,NaN
22,Skoda,Enyaq iV 50,10.0,160,290,179,230,Yes,RWD,Type 2 CCS,SUV,C,5,35000,NaN
23,Audi,e-tron GT,3.5,240,425,197,850,Yes,AWD,Type 2 CCS,Sedan,F,4,125000,NaN
24,Tesla,Model 3 Long Range Performance,3.4,261,435,167,910,Yes,AWD,Type 2 CCS,Sedan,D,5,61480,NaN
25,Volkswagen,ID.4,7.5,160,420,183,560,Yes,RWD,Type 2 CCS,SUV,C,5,45000,NaN
26,Volkswagen,ID.3 Pro,9.0,160,350,166,490,Yes,RWD,Type 2 CCS,Hatchback,C,5,33000,NaN
27,Volvo,XC40 P8 AWD Recharge,4.9,180,375,200,470,Yes,AWD,Type 2 CCS,SUV,C,5,60437,NaN
28,BMW,i3 120 Ah,7.3,150,235,161,270,Yes,RWD,Type 2 CCS,Hatchback,B,4,38017,NaN
29,Peugeot,e-2008 SUV,8.5,150,250,180,380,Yes,FWD,Type 2 CCS,SUV,B,5,34361,NaN
30,Audi,e-tron 50 quattro,6.8,190,280,231,450,Yes,AWD,Type 2 CCS,SUV,E,5,67358,NaN
31,Kia,e-Niro 64 kWh,7.8,167,370,173,350,Yes,FWD,Type 2 CCS,SUV,C,5,38105,NaN
32,Renault,Zoe ZE50 R110,11.4,135,315,165,230,Yes,FWD,Type 2 CCS,Hatchback,B,5,31184,NaN
33,Tesla,Cybertruck Tri Motor,3.0,210,750,267,710,Yes,AWD,Type 2 CCS,Pickup,N,6,75000,NaN
34,Mazda,MX-30,9.0,150,180,178,240,Yes,FWD,Type 2 CCS,SUV,C,5,32646,NaN
35,Nissan,Leaf e+,7.3,157,325,172,390,Yes,FWD,Type 2 CHAdeMO,Hatchback,C,5,37237,NaN
36,Lexus,UX 300e,7.5,160,270,193,190,Yes,FWD,Type 2 CHAdeMO,SUV,C,5,50000,NaN
37,CUPRA,el-Born,6.5,160,425,181,570,Yes,RWD,Type 2 CCS,Hatchback,C,4,45000,NaN
38,Renault,Zoe ZE50 R135,9.5,140,310,168,230,Yes,FWD,Type 2 CCS,Hatchback,B,5,33133,NaN
39,Mercedes,EQA,5.0,200,350,171,440,Yes,AWD,Type 2 CCS,SUV,C,5,45000,NaN
40,Tesla,Model S Long Range,3.8,250,515,184,560,Yes,AWD,Type 2,Liftback,F,5,79990,NaN
41,Hyundai,Kona Electric 39 kWh,9.9,155,255,154,210,Yes,FWD,Type 2 CCS,SUV,B,5,33971,NaN
42,Audi,e-tron Sportback 55 quattro,5.7,200,380,228,610,Yes,AWD,Type 2 CCS,SUV,E,5,81639,NaN
43,Skoda,CITIGOe iV,12.3,130,195,166,170,Yes,FWD,Type 2 CCS,Hatchback,A,4,24534,NaN
44,SEAT,Mii Electric,12.3,130,195,166,170,Yes,FWD,Type 2 CCS,Hatchback,A,4,20129,NaN
45,Kia,e-Soul 64 kWh,7.9,167,365,175,340,Yes,FWD,Type 2 CCS,SUV,B,5,36837,NaN
46,Opel,Ampera-e,7.3,150,335,173,210,Yes,FWD,Type 2 CCS,MPV,B,5,41906,NaN
47,Porsche,Taycan 4S,4.0,250,365,195,730,Yes,AWD,Type 2 CCS,Sedan,F,4,102945,NaN
48,Lightyear,One,10.0,150,575,104,540,Yes,AWD,Type 2 CCS,Liftback,F,5,149000,NaN
49,Aiways,U5,9.0,150,335,188,350,Yes,FWD,Type 2 CCS,SUV,C,5,36057,NaN

In [32]:
df.tail(6)

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro,Age
97,Byton,M-Byte 72 kWh 2WD,7.5,190,325,222,420,Yes,RWD,Type 2 CCS,SUV,E,5,53500,NaN
98,Nissan,Ariya 63kWh,7.5,160,330,191,440,Yes,FWD,Type 2 CCS,Hatchback,C,5,45000,NaN
99,Audi,e-tron S Sportback 55 quattro,4.5,210,335,258,540,Yes,AWD,Type 2 CCS,SUV,E,5,96050,NaN
100,Nissan,Ariya e-4ORCE 63kWh,5.9,200,325,194,440,Yes,AWD,Type 2 CCS,Hatchback,C,5,50000,NaN
101,Nissan,Ariya e-4ORCE 87kWh Performance,5.1,200,375,232,450,Yes,AWD,Type 2 CCS,Hatchback,C,5,65000,NaN
102,Byton,M-Byte 95 kWh 2WD,7.5,190,400,238,480,Yes,AWD,Type 2 CCS,SUV,E,5,62000,NaN

In [34]:
groups = df.groupby("Range_Km")

In [35]:
groups.groups

{95: [77, 91], 100: [82], 130: [57], 160: [68], 170: [4, 55], 180: [34], 185: [19], 190: [6, 66], 195: [17, 43, 44], 220: [11, 18], 225: [74], 230: [70, 96], 235: [28, 75], 250: [14, 29, 56, 58, 85, 94], 255: [41, 52, 60], 270: [1, 36], 275: [7, 20], 280: [30], 290: [22], 295: [87], 310: [8, 38], 315: [32], 320: [89, 90], 325: [35, 97, 100], 330: [84, 98], 335: [46, 49, 99], 340: [78, 80, 95], 350: [26, 39], 360: [3, 83], 365: [45, 47, 50, 63, 92], 370: [10, 31], 375: [16, 27, 101], 380: [42], 385: [72], 390: [73, 79, 86], 400: [2, 9, 12, 71, 88, 102], 410: [61, 76], 420: [25, 53, 93], 425: [21, 23, 37, 65], 430: [69], 435: [24], 440: [15, 62, 81], 450: [0, 13, 54, 64], 460: [67], 505: [59], 515: [40], 575: [48], 610: [5], 750: [33], 970: [51]}

In [36]:
df.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro,Age
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480,NaN
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000,22.0
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440,24.0
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040,NaN
4,Honda,e,9.5,145,170,168,190,Yes,RWD,Type 2 CCS,Hatchback,B,4,32997,NaN

In [40]:
df.groupby("Seats")  ["Range_Km"].mean()

Seats
2     97.500000
4    309.523810
5    343.028169
6    533.333333
7    374.166667
Name: Range_Km, dtype: float64

In [41]:
type(groups)

pandas.api.typing.DataFrameGroupBy